### ISSUE TITLE
Return True does not add value

### ISSUE THREAD

**Issue by depoon** [s3corp-github/S3_WeatherApp_iOS_DonVo#4]
https://github.com/s3corp-github/S3_WeatherApp_iOS_DonVo/blob/fab9a42ebea2d3dd24cbd7c02ac6d6acaf9fbb51/WeatherApp/UI/Home/SearchViewModel.swift#L64

does not add any value to return boolean or hard coding `true`

**Comment by DonMartialMinh** [comment]
Thank you for your review, I have fixed this issue. Please let me know if there is any problem or what I can do to improve my code.
