### ISSUE TITLE
`Network.shared()` not injected in SearchService 

### ISSUE THREAD

**Issue by davidlamys** [s3corp-github/S3_WeatherApp_iOS_DonVo#6]
It looks like this is not really testing the algorithm
https://github.com/s3corp-github/S3_WeatherApp_iOS_DonVo/blob/master/WeatherAppTests/SearchServiceTests.swift#L94

ie, one can delete 
https://github.com/s3corp-github/S3_WeatherApp_iOS_DonVo/blob/master/WeatherApp/Service/SearchService.swift#L24-L26

and the tests will still pass.

Please help to inject `Network.shared()` and rewrite the `test_whenRetrievesCityListAlreadyCached_thenContainsCityList` accordingly

**Comment by DonMartialMinh** [comment]
Thank you for your review, I have fixed this issue. Please let me know if there is any problem or what I can do to improve my code.
